version: "3"
services:
  alpha:
    image: deltan123/alpha:0.0.1-SNAPSHOT
    ports:
    - 8001:8001
    environment:
     BOOT_MONGO_URI: app
    networks:
      - alpha-app
    depends_on:
    - app
  app:
    image: deltan123/spring-boot-mongodb-example:0.0.1-SNAPSHOT
    ports:
    - 8080:8080
    networks:
      - alpha-app
    depends_on:
    - mongodb
    environment:
      RDS_HOSTNAME: mongodb
    links:
    - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    ports:
    - 27017:27017
    networks:
      - alpha-app
    volumes:
    - mongodata:/data/db
volumes:
  mongodata:
networks:
  alpha-app: